// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AllRecipesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testViewAllRecipes() {
    // Test name: TestViewAllRecipes
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://seng-401-on-the-house.web.app/");
    // 2 | click | css=.MuiButton-containedWarning | 
    driver.findElement(By.cssSelector(".MuiButton-containedWarning")).click();
    // 3 | assertText | css=.MuiGrid-root:nth-child(1) .MuiCardHeader-root .MuiTypography-root:nth-child(1) | Beef dish
    assertThat(driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(1) .MuiCardHeader-root .MuiTypography-root:nth-child(1)")).getText(), is("Beef dish"));
  }
}
