// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testLoginValid() {
    // Test name: TestLoginValid
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://seng-401-on-the-house.web.app/");
    // 2 | click | css=.MuiButton-containedSuccess | 
    driver.findElement(By.cssSelector(".MuiButton-containedSuccess")).click();
    // 3 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 4 | type | id=email | seng401g23@gmail.com
    driver.findElement(By.id("email")).sendKeys("seng401g23@gmail.com");
    // 5 | click | id=password | 
    driver.findElement(By.id("password")).click();
    // 6 | mouseOver | css=.MuiButton-root | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | type | id=password | passwordg23
    driver.findElement(By.id("password")).sendKeys("passwordg23");
    // 8 | click | css=.MuiButton-root | 
    driver.findElement(By.cssSelector(".MuiButton-root")).click();
    // 9 | assertText | xpath=//button[2] | LOGOUT
    assertThat(driver.findElement(By.xpath("//button[2]")).getText(), is("LOGOUT"));
  }
  @Test
  public void testLogout() {
    // Test name: TestLogout
    // Step # | name | target | value
    // 1 | open | /dashboard | 
    driver.get("https://seng-401-on-the-house.web.app/dashboard");
    // 2 | waitForElementPresent | css=.MuiButton-root | 30000
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".MuiButton-root")));
    }
    // 3 | assertText | xpath=(//button[@type='button'])[2] | LOGOUT
    assertThat(driver.findElement(By.xpath("(//button[@type=\'button\'])[2]")).getText(), is("LOGOUT"));
    // 4 | click | css=.MuiButton-root | 
    driver.findElement(By.cssSelector(".MuiButton-root")).click();
    // 5 | click | css=.MuiButton-containedSuccess | 
    driver.findElement(By.cssSelector(".MuiButton-containedSuccess")).click();
    // 6 | assertText | css=.MuiTypography-h5 | Sign in
    assertThat(driver.findElement(By.cssSelector(".MuiTypography-h5")).getText(), is("Sign in"));
  }
  @Test
  public void testLoginInvalidPassword() {
    // Test name: TestLoginInvalidPassword
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://seng-401-on-the-house.web.app/");
    // 2 | click | css=.MuiButton-containedSuccess | 
    driver.findElement(By.cssSelector(".MuiButton-containedSuccess")).click();
    // 3 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 4 | type | id=email | seng401g23@gmail.com
    driver.findElement(By.id("email")).sendKeys("seng401g23@gmail.com");
    // 5 | click | id=password | 
    driver.findElement(By.id("password")).click();
    // 6 | mouseOver | css=.MuiButton-root | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | type | id=password | asudaushduashduha
    driver.findElement(By.id("password")).sendKeys("asudaushduashduha");
    // 8 | click | css=.MuiButton-root | 
    driver.findElement(By.cssSelector(".MuiButton-root")).click();
    // 9 | waitForElementPresent | css=.MuiAlert-root | 30000
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".MuiAlert-root")));
    }
    // 10 | assertText | css=.MuiAlert-message | auth/wrong-password
    assertThat(driver.findElement(By.cssSelector(".MuiAlert-message")).getText(), is("auth/wrong-password"));
  }
}
