// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class MyRecipesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testAuthorizedViewMyRecipes() {
    // Test name: TestAuthorizedViewMyRecipes
    // Step # | name | target | value
    // 1 | open | /dashboard | 
    driver.get("https://seng-401-on-the-house.web.app/dashboard");
    // 2 | waitForElementPresent | css=.MuiButton-root | 30000
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".MuiButton-root")));
    }
    // 3 | assertText | xpath=(//button[@type='button'])[2] | LOGOUT
    assertThat(driver.findElement(By.xpath("(//button[@type=\'button\'])[2]")).getText(), is("LOGOUT"));
    // 4 | click | css=a:nth-child(1) .MuiSvgIcon-root | 
    driver.findElement(By.cssSelector("a:nth-child(1) .MuiSvgIcon-root")).click();
    // 5 | assertText | css=.css-12ok3km | My Recipes
    assertThat(driver.findElement(By.cssSelector(".css-12ok3km")).getText(), is("My Recipes"));
  }
  @Test
  public void testUnauthorizedViewMyRecipes() {
    // Test name: TestUnauthorizedViewMyRecipes
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://seng-401-on-the-house.web.app/");
    // 2 | click | css=.MuiButton-containedWarning | 
    driver.findElement(By.cssSelector(".MuiButton-containedWarning")).click();
    // 3 | mouseOver | css=a:nth-child(1) path | 
    {
      WebElement element = driver.findElement(By.cssSelector("a:nth-child(1) path"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | css=a:nth-child(1) path | 
    driver.findElement(By.cssSelector("a:nth-child(1) path")).click();
    // 5 | assertText | css=.MuiTypography-h5 | Sign in
    assertThat(driver.findElement(By.cssSelector(".MuiTypography-h5")).getText(), is("Sign in"));
  }
  @Test
  public void testDeleteRecipe() {
    // Test name: TestDeleteRecipe
    // Step # | name | target | value
    // 1 | open | /dashboard | 
    driver.get("https://seng-401-on-the-house.web.app/dashboard");
    // 2 | waitForElementPresent | css=.MuiButton-root | 30000
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".MuiButton-root")));
    }
    // 3 | assertText | xpath=(//button[@type='button'])[2] | LOGOUT
    assertThat(driver.findElement(By.xpath("(//button[@type=\'button\'])[2]")).getText(), is("LOGOUT"));
    // 4 | click | css=a:nth-child(1) .MuiSvgIcon-root | 
    driver.findElement(By.cssSelector("a:nth-child(1) .MuiSvgIcon-root")).click();
    // 5 | assertElementPresent | xpath=//div[@id='root']/div/div/main/div[2]/div | 
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@id=\'root\']/div/div/main/div[2]/div"));
      assert(elements.size() > 0);
    }
    // 6 | click | css=.css-1hfx6hj | 
    driver.findElement(By.cssSelector(".css-1hfx6hj")).click();
    // 7 | click | css=.css-16hxacb | 
    driver.findElement(By.cssSelector(".css-16hxacb")).click();
    // 8 | assertElementNotPresent | xpath=//div[@id='root']/div/div/main/div[2]/div | 
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@id=\'root\']/div/div/main/div[2]/div"));
      assert(elements.size() == 0);
    }
  }
  @Test
  public void testEditRecipe() {
    // Test name: TestEditRecipe
    // Step # | name | target | value
    // 1 | open | /dashboard | 
    driver.get("https://seng-401-on-the-house.web.app/dashboard");
    // 2 | waitForElementPresent | css=.MuiButton-root | 30000
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".MuiButton-root")));
    }
    // 3 | assertText | xpath=(//button[@type='button'])[2] | LOGOUT
    assertThat(driver.findElement(By.xpath("(//button[@type=\'button\'])[2]")).getText(), is("LOGOUT"));
    // 4 | click | css=a:nth-child(1) .MuiSvgIcon-root | 
    driver.findElement(By.cssSelector("a:nth-child(1) .MuiSvgIcon-root")).click();
    // 5 | assertElementPresent | xpath=//div[@id='root']/div/div/main/div[2]/div | 
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@id=\'root\']/div/div/main/div[2]/div"));
      assert(elements.size() > 0);
    }
    // 6 | click | css=.MuiButtonBase-root > a | 
    driver.findElement(By.cssSelector(".MuiButtonBase-root > a")).click();
    // 7 | click | id=:rs: | 
    driver.findElement(By.id(":rs:")).click();
    // 8 | type | id=:rs: | Edited Test Post
    driver.findElement(By.id(":rs:")).sendKeys("Edited Test Post");
    // 9 | click | css=.MuiButton-containedInfo | 
    driver.findElement(By.cssSelector(".MuiButton-containedInfo")).click();
    // 10 | waitForElementPresent | xpath=//div[@id='root']/div/div/main/div[2]/div | 30000
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[@id=\'root\']/div/div/main/div[2]/div")));
    }
    // 11 | assertText | css=.css-j0dhdu | Edited Test Post
    assertThat(driver.findElement(By.cssSelector(".css-j0dhdu")).getText(), is("Edited Test Post"));
  }
}
